name: Build

on:
  workflow_dispatch:
  pull_request:
  
permissions:
  contents: read 
  packages: read

jobs:
  setup:
    runs-on: ["self-hosted", "run-${{github.run_id}}"]
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Clone and Checkout the Repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: true

      - name: Install NPM Packages
        run: npm install
        shell: bash

  build-plugin:
    runs-on: ["self-hosted", "run-${{github.run_id}}"]
    needs: setup
    steps:
      - name: Build the Plugin
        run: npm run build
        shell: bash

  upload-plugin:
    runs-on: ["self-hosted", "run-${{github.run_id}}"]
    needs: build-plugin
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps: 
      - name: Compress Plugin Source
        shell: bash
        run: tar -czf ./obsidian-agile-plugin.tar.gz -C ./dist .

      - name: Check File is Made
        shell: bash
        run: ls -la ./obsidian-agile-plugin.tar.gz

      - name: Upload Standalone Source
        uses: actions/upload-artifact@v4
        with:
          name: obsidian-agile-plugin.tar.gz
          path: ./obsidian-agile-plugin.tar.gz
          retention-days: 1